### ISSUE TITLE
link from gmaps not recognized

### ISSUE THREAD

**Issue by nutpantz** [jakubvalenta/geoshare#2]
A link sent from gmaps
(Google maps in a privacy web view app}
https://gitlab.com/divested-mobile/maps
https://f-droid.org/packages/us.spotco.maps/
When shared your app does not show up as a app i can share to.

https://www.google.com/maps/place/49.364389,+-121.432834/@49.3534573,-121.4534333,12z/data=!4m4!3m3!8m2!3d49.3643895!4d-121.432834

Other apps like organic maps and osmand show as a shareable destination.

Pixel 8 pro A 14

**Comment by jakubvalenta** [comment]
Thank you for the bug report! The problem was that GMaps WV already shares geo: URLs instead of Google Maps URLs (you can see the [code](https://gitlab.com/divested-mobile/maps/-/blob/f162a251ed0277b67061db75b99a84e0e90d7bcb/app/src/main/java/us/spotco/maps/MainActivity.java#L423)). This makes Geo Share not necessary in this case.

Nevertheless, I've added support for receiving geo: URLs to Geo Share. When that happens, the geo: URL is shared further unchanged. This should result in the expected user experience. The change is included in [v1.1.0](https://github.com/jakubvalenta/geoshare/releases/tag/v1.1.0).

**Comment by jakubvalenta** [comment]
I've reverted the fix, because it was confusing when the app was able to consume as well as produce geo: links. I've added information about GMaps WV compatibility to the README and the FAQ screen:

![Image](https://github.com/user-attachments/assets/fe6e8e8c-6f74-4a3d-925b-eedd16bec9eb)
